<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the names of the copyright holders nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org</groupId>
    <artifactId>javacc</artifactId>
    <version>8.1.0-SNAPSHOT</version>
  </parent>

  <groupId>org.javacc</groupId>
  <artifactId>core</artifactId>
  <!--  <version>8.1.0-SNAPSHOT</version>-->
  <packaging>jar</packaging>

  <name>JavaCC Core</name>
  <description>Core module of JavaCC</description>
  <url>https://github.com/javacc/javacc-8-core</url>
  <inceptionYear>1996</inceptionYear>

  <!-- 
       javacc core pom
       defines specific settings for its build
  -->

  <organization>
    <name>javacc.org</name>
    <url>https://javacc.github.io/javacc/</url>
  </organization>

  <scm>
    <url>https://github.com/javacc/javacc-8-core</url>
    <connection>scm:git:https://github.com/javacc/javacc-8-core.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/javacc/javacc-8-core.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <properties>
    <net-javacc-bootstrap.version>4.2</net-javacc-bootstrap.version>
    <org-javacc-bootstrap.version>8.0.1</org-javacc-bootstrap.version>
    <!--    <org-javacc-bootstrap.version>8.1.0</org-javacc-bootstrap.version>-->

    <!-- TODO temp remove -->
    <javacc-maven-plugin.version>3.0.3</javacc-maven-plugin.version>
  </properties>

  <!-- run 'mvn -Psnapshot,release -DshowAllPhases=true buildplan:list buildplan:list-phases'
             to list the project/module build plan -->

  <build>

    <pluginManagement>
      <plugins>
        <!-- all in parent javacc-8/pom.xml -->
      </plugins>
    </pluginManagement>

    <plugins>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/*Test.java</exclude>
          </excludes>
        </configuration>
      </plugin>

      <plugin>
        <!--        <groupId>org.codehaus.mojo</groupId>-->
        <groupId>org.javacc.plugin</groupId>
        <artifactId>javacc-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <!-- TODO use a more recent bootstrap -->
            <!-- dual tests could be done via an additional specific profile -->
            <groupId>net.java.dev.javacc</groupId>
            <artifactId>javacc</artifactId>
            <version>${net-javacc-bootstrap.version}</version>
            <!--            <groupId>org.javacc.generator</groupId>-->
            <!--            <artifactId>java</artifactId>-->
            <!--            <version>${org-javacc-bootstrap.version}</version>-->
            <scope>runtime</scope>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>jjt-jcc</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>jjtree-javacc</goal>
            </goals>
            <configuration>
              <excludes>
                <exclude>**/parser/**</exclude>
              </excludes>
            </configuration>
          </execution>
          <execution>
            <id>jcc</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>javacc</goal>
            </goals>
            <configuration> </configuration>
          </execution>
          <!-- sometimes it may be necessary to switch back to jjtree only goal for debugging -->
          <!--          <execution>-->
          <!--            <id>jjt</id>-->
          <!--            <phase>generate-sources</phase>-->
          <!--            <goals>-->
          <!--              <goal>jjtree</goal>-->
          <!--            </goals>-->
          <!--            <configuration>-->
          <!--              <excludes>-->
          <!--                <exclude>**/parser/**</exclude>-->
          <!--              </excludes>-->
          <!--            </configuration>-->
          <!--          </execution>-->
          <!--          <execution>-->
          <!--            <id>jcc</id>-->
          <!--            <phase>generate-sources</phase>-->
          <!--            <goals>-->
          <!--              <goal>javacc</goal>-->
          <!--            </goals>-->
          <!--            <configuration>-->
          <!--              <sourceDirectory>target/generated-sources/jjtree</sourceDirectory>-->
          <!--            </configuration>-->
          <!--          </execution>-->

        </executions>
      </plugin>

    </plugins>
  </build>

</project>

